### ISSUE TITLE
Consider adding action to toggle ocr functionality

### ISSUE THREAD

**Issue by knausj85** [wolfmanstout/talon-gaze-ocr#14]
Suggestion: Add an action toggle ocr on/off. 

That way, folks can enable the functionality as they see fit. For instance, I have a switch that toggles everything  when I walk away/come back (speech, noise, zoom mouse, etc).  

Might be useful, particularly for folks with Tobii 4Cs which have an unfortunate habit of dying.

**Comment by wolfmanstout** [comment]
Just to clarify: the main thing you are looking to turn off is the eye tracker? The OCR itself only runs when needed in commands, but we do track recent gaze history (a few seconds) in the background, which means the eye tracker is always on. I could add actions to disable/enable that and the OCR commands would behave as if there is no eye tracker (they would search the whole screen).

**Comment by knausj85** [comment]
Yep, turning off the tracker is the request since OCR is performed only as a result of command. I figured as much, but wasn't sure.

This below sounds like a great solution to me:
> add actions to disable/enable that and the OCR commands would behave as if there is no eye tracker (they would search the whole screen).

**Comment by wolfmanstout** [comment]
Fixed in afe5f9e1f108409daeeb959f685b7b8b506cee29

Try "ocr tracker off" and "ocr tracker on".
