### ISSUE TITLE
No gaze history available

### ISSUE THREAD

**Issue by brief** [wolfmanstout/talon-gaze-ocr#22]
I use Gaze OCR without an eye tracker and have disabled `ocr_connect_tracker` in my settings. Every time I use Gaze, I get a `IO No gaze history available` message in my Talon log.

Is it looking for something besides data from the tracker?

**Comment by wolfmanstout** [comment]
This is expected if `ocr_connect_tracker` is disabled. Is your concern just that this is a spammy log?

**Comment by brief** [comment]
It is.

Makes sense for `ocr_connect_tracker` to be on by default and to log messages when it can't connect to a tracker, but I was surprised to keep seeing them when I explicitly disabled it.

Possible to mute them when `ocr_connect_tracker` is turned off in the settings? Or is there a concern with doing that?

**Comment by wolfmanstout** [comment]
Yeah that's a reasonable request.

**Comment by wolfmanstout** [comment]
This should now be fixed.
