### ISSUE TITLE
Additional Documentation

### ISSUE THREAD

**Issue by C-Loftus** [wolfmanstout/talon-gaze-ocr#23]
It would be greatly appreciated if additional documentation could be included in the Talon file. Currently, some of the captures are particularly verbose and lack clarity regarding valid commands. This can be especially confusing for new users who may not be familiar with the functionality of captures or lists, and simply desire a basic understanding of what commands are considered valid.

For instance `<user.prose_range>`   might be difficult to understand for a new Talon user  since they would have to go to the python and then have a general understanding of how the capture is formed in the first place in order to deduce its grammar.

It appears that certain syntax mentioned in previous documentation may no longer be valid. For instance, in the following video (https://www.youtube.com/watch?v=qkFy66WF3bU), the command "select words" is mentioned using the `select` command. However, it remains unclear whether this is still a valid range specifier.

 I don't think this needs to be anything particularly complicated, but rather to have a few string comments above  the talon commands as examples ( only for the more complicated captures) without the need to delve into Python.

 it would be nice for the select statements to also clarify in what contexts it might not work (PDFs ? Slideshows? etc)

**Comment by wolfmanstout** [comment]
Thanks, this is a very reasonable request. I will try to pick this up soon.

**Comment by wolfmanstout** [comment]
Let me know if there is more you were looking for. I didn't want to get too much into known issues -- there are quite a few of them and I try to document those in the README.

**Comment by C-Loftus** [comment]
Thanks for doing this, this looks really helpful for newer users. And yes, that makes sense regarding issues. No worries about that totally understandable
