### ISSUE TITLE
gaze-ocr not starting on linux mint

### ISSUE THREAD

**Issue by jarrodharvey** [wolfmanstout/talon-gaze-ocr#24]
Gaze OCR will not start on my Linux Mint installation.  I get the following error related to a failed package import.  Any ideas for a possible fix?

2023-11-04 17:06:29.796 ERROR user.talon-gaze-ocr.gaze_ocr_talon (/home/jarrod/.talon/user/talon-gaze-ocr/gaze_ocr_talon.py) import failed
   54:                                           lib/python3.11/threading.py:995 * # loader thread
   53:                                           lib/python3.11/threading.py:1038* 
   52:                                           lib/python3.11/threading.py:975 * 
   51:                                               app/resources/loader.py:852 | 
   50:                                               app/resources/loader.py:784 | 
   49:                                               app/resources/loader.py:644 | 
   48:                                               app/resources/loader.py:660 | 
   47:                                               app/resources/loader.py:715 | 
   46:                                               app/resources/loader.py:425 | # [stack splice]
   45:                                  lib/python3.11/importlib/__init__.py:126 | 
   44:                                               app/resources/loader.py:240 | 
   43:                                               app/resources/loader.py:235 | 
   42:                                 user/talon-gaze-ocr/gaze_ocr_talon.py:34  | import gaze_ocr
   41:                                                                             ^^^^^^^^^^^^^^^
   40:                                               app/resources/loader.py:359 | 
   39:                     lib/python3.11/site-packages/gaze_ocr/__init__.py:1   | from ._gaze_ocr import *
   38:                                               app/resources/loader.py:359 | 
   37:                    lib/python3.11/site-packages/gaze_ocr/_gaze_ocr.py:14  | from screen_ocr import Reader, ScreenC..
   36:                                               app/resources/loader.py:359 | 
   35:                   lib/python3.11/site-packages/screen_ocr/__init__.py:1   | from ._screen_ocr import *
   34:                                               app/resources/loader.py:359 | 
   33:                lib/python3.11/site-packages/screen_ocr/_screen_ocr.py:36  | from . import _easyocr
   32:                                                                             ^^^^^^^^^^^^^^^^^^^^^^
   31:                                               app/resources/loader.py:359 | 
   30:                   lib/python3.11/site-packages/screen_ocr/_easyocr.py:1   | import easyocr
   29:                                               app/resources/loader.py:359 | 
   28:                      lib/python3.11/site-packages/easyocr/__init__.py:1   | from .easyocr import Reader
   27:                                               app/resources/loader.py:359 | 
   26:                       lib/python3.11/site-packages/easyocr/easyocr.py:3   | from .recognition import get_recognize..
   25:                                               app/resources/loader.py:359 | 
   24:                   lib/python3.11/site-packages/easyocr/recognition.py:2   | import torch
   23:                                               app/resources/loader.py:359 | 
   22:                        lib/python3.11/site-packages/torch/__init__.py:1465| from . import _meta_registrations
   21:                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   20:                                               app/resources/loader.py:359 | 
   19:             lib/python3.11/site-packages/torch/_meta_registrations.py:7   | from torch._decomp import _add_op_to_r..
   18:                                               app/resources/loader.py:359 | 
   17:                lib/python3.11/site-packages/torch/_decomp/__init__.py:169 | import torch._decomp.decompositions
   16:                                               app/resources/loader.py:359 | 
   15:          lib/python3.11/site-packages/torch/_decomp/decompositions.py:22  | from torch.fx.experimental.symbolic_sh..
   14:                                               app/resources/loader.py:359 | 
   13: lib/python3.11/site-packages/torch/fx/experimental/symbolic_shapes.py:29  | import sympy  # type: ignore[import]
   12:                                                                             ^^^^^^^^^^^^
   11:                                               app/resources/loader.py:359 | 
   10:                        lib/python3.11/site-packages/sympy/__init__.py:30  | from sympy.core.cache import lazy_func..
    9:                                               app/resources/loader.py:359 | 
    8:                   lib/python3.11/site-packages/sympy/core/__init__.py:9   | from .expr import Expr, AtomicExpr, Un..
    7:                                               app/resources/loader.py:359 | 
    6:                       lib/python3.11/site-packages/sympy/core/expr.py:42  | @sympify_method_args
    5:                                                                              ^^^^^^^^^^^^^^^^^^^
    4:                 lib/python3.11/site-packages/sympy/core/decorators.py:180 | setattr(cls, attrname, obj.make_wrappe..
    3:                                                                                               ^^^^^^^^^^^^^^^^^^^^^
    2:                 lib/python3.11/site-packages/sympy/core/decorators.py:215 | nargs = func.__code__.co_argcount
    1:                                                                                     ^^^^^^^^^^^^^
AttributeError: __code__

**Comment by wolfmanstout** [comment]
As noted in the README, Linux is not supported as the OCR API in Talon is not supported for Linux. Some folks have been successful in getting this to work so you can check pinned messages in the Talon ext-gaze-ocr Slack channel.
