### ISSUE TITLE
No eye tracking available on mac

### ISSUE THREAD

**Issue by shriharip** [wolfmanstout/talon-gaze-ocr#25]
Sorry if this is a help query.

But I just cloned this inside `.talon/user` directory.
I have cloned the [community repo](https://github.com/talonhub/community) 

My dir sturcutre under `.talon/user` is 
Community
talon-gaze-ocr

However, on talon menu item. I do not get ocr functionalities activated. Am I missing something. Please help. Thanks

**Comment by wolfmanstout** [comment]
Did you figure this out? There is no menu entry for this, it just adds commands. I would recommend posting on the #ext-gaze-ocr for questions like this. Thanks!
