### ISSUE TITLE
OCR identifies the talon accessibility whitetext

### ISSUE THREAD

**Issue by BoltonBailey** [wolfmanstout/talon-gaze-ocr#27]
Often, the OCR mechanism will identify the text of the exact command I have just issued as a thing it thinks I might want to click on. This is somewhat annoying, because it means that I have to say "choose one" after every click command I issue.

<img width="1512" alt="Screenshot 2024-07-02 at 1 38 39 PM" src="https://github.com/wolfmanstout/talon-gaze-ocr/assets/8030599/d486299f-2b3b-444e-b39a-719cd825e420">

**Comment by wolfmanstout** [comment]
I am following up with the author of Talon to see what can be done about this. One workaround is to use [Talon HUD](https://github.com/chaosparrot/talon_hud) instead of the built-in subtitles. I automatically turn this UI off before taking a screenshot, so it will not interfere.

**Comment by wolfmanstout** [comment]
Fixed in the latest Talon Beta! No changes needed to this repo.
