### ISSUE TITLE
Black background (not translucent) / missing text and ugly font choice on Windows

### ISSUE THREAD

**Issue by nriley** [wolfmanstout/talon-gaze-ocr#7]
Here's a workaround (actually simpler than what you do now) - create debug/disambiguation canvases using `Canvas.from_screen`, for example:

    disambiguation_canvas = Canvas.from_screen(screen.main())

I found the appearance is improved if you remove `c.paint.typeface = "arial"` - Skia picks something OS-specific which looks better.

Here's how it looks now with everything fixed:

![image](https://user-images.githubusercontent.com/68303/191131326-0237d180-d208-4118-a5c5-8d4b254eba57.png)

Also would recommend not using `embolden` (synthetic bold) when fonts should have true bold. I was able to construct a true bold system font like this:

```python
                from talon.skia.typeface import Typeface, Fontstyle
                c.paint.typeface = Typeface.from_name('', Fontstyle.new(weight=700, width=5))
```
Or to go back to the system font:
```python
               c.paint.typeface = ''
```

**Comment by wolfmanstout** [comment]
These all sound like great changes! Do you want to just send me a pull request? If for some reason that would be difficult, I can make the changes myself.

**Comment by nriley** [comment]
﻿Sure, I can do that, it may be a week or so - very busy this week and traveling this weekend.NicholasOn Sep 19, 2022, at 11:42 PM, James Stout ***@***.***> wrote:﻿
These all sound like great changes! Do you want to just send me a pull request? If for some reason that would be difficult, I can make the changes myself.

**Comment by nriley** [comment]
Sure, I can do that, it may be a week or so - very busy this week and traveling this weekend.NicholasOn Sep 19, 2022, at 11:42 PM, James Stout ***@***.***> wrote:﻿
These all sound like great changes! Do you want to just send me a pull request? If for some reason that would be difficult, I can make the changes myself.
